
version: 2
jobs:
  build:
    working_directory: /tmp/vasko
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout

      - run:
          name: Installing dependencies.
          command: npm install

      - run:
          name: Run tests
          command: NODE_ENV="ci" npm test

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

      - deploy:
          name: Deploy to S3 if branch is Master.
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm publish
            fi